version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - PORT=8000
      - API_BASE_URL=http://fastapi:8000
    depends_on:
      - postgres
    networks:
      - twintone-network

  streamlit:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - API_BASE_URL=http://fastapi:8000
    depends_on:
      - fastapi
    networks:
      - twintone-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - twintone-network

volumes:
  postgres_data:

networks:
  twintone-network:
    driver: bridge